baseURL = "https://laujay.com/"
languageCode = "zh-CN"
title = "世界的过客"
canonifyurls = true

theme = "hugo-kiera"
copyright = "Copyright &copy; 2016 ~ 2020 - Jay Lau"

paginate = 10

summaryLength = 3
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Jay Lau"
  github = "lau-jay"

[params]
  tagline = "每个人获得的东西都恰好是他值得获得的东西"
  customCSS = []
  favicon = "/img/favicon.ico"
