baseURL = "https://laujay.com/"
languageCode = "zh-CN"
title = "世界的过客"
canonifyurls = true
ignoreLogs = ['warning-goldmark-raw-html']

theme = "hugo-kiera"
copyright = "Copyright &copy; 2016 ~ 2025 - Jay Lau|Theme by [kiera](https://github.com/funkydan2/hugo-kiera)"

paginate = 10

summaryLength = 3
enableEmoji = true
pygmentsCodeFences = true


disqusShortname = "lau-jay"
[services.disqus]
  shortname = "lau-jay"

[services.googleAnalytics]
    ID = "UA-91611718-2"

[author]
  name = "Jay Lau"
  github = "lau-jay"

[params]
  author = "Jay Lau"
  tagline = "每个人获得的东西都恰好是他值得获得的东西"
  customCSS = []
  favicon = "/img/favicon.ico"
  homepageLength = 100
  commentAutoload = true

# uncomment to enable the Tags link on the main toolbar
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 1

# uncomment to enable the Categories link on the main toolbar
[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 1
