# .github/workflows/build.yml

name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Building..."
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.128.0" # 指定你的 Hugo 版本
        env:
          DEPLOY_REPO: lau-jay/lau-jay.github.io
          DEPLOY_BRANCH: master
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          TZ: Asia/Shanghai
