# .github/workflows/build.yml

name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Debug directory structure
        run: ls -la
      - name: "Building..."
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.128.0" # 指定你的 Hugo 版本

      - name: "Build"
        run: |
          # 打印目录结构确认文件存在（调试用）
          ls -la
          # 执行构建
          hugo --minify

      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }} # 需提前配置 SSH Deploy Key
          external_repository: lau-jay/lau-jay.github.io # 目标仓库
          TZ: Asia/Shanghai
